image: golang:latest

variables:
  IMAGE_NAME: maiyzaza/demo-app
  IMAGE_TAG: latest

stages:
  - database
  - build
  - deploy

database:
  stage: database
  script:
    -  |
        cat << EOF > .env
              REMOTE_DB_URL="$DB_CONNECTION"
        EOF
        ls -la
        cat .env

build_image:
  stage: build
  image: docker:24.0.4-cli
  services:
    - docker:24.0.4-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS && 
      docker build -t $IMAGE_NAME:$IMAGE_TAG . &&
      docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@146.190.98.250 "
      container_ids=$(docker ps -q)
      if [ -z "$container_ids" ]; then
        echo "No containers are currently running."
        docker images -q | xargs -r docker rmi &&
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG
      else
        echo "Stopping and removing containers..."
        echo "$container_ids" | xargs docker stop
        echo "$container_ids" | xargs docker rm
        docker images -q | xargs -r docker rmi &&
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG
      fi"
      