image: golang:latest

variables:
  IMAGE_NAME: maiyzaza/demo-app
  IMAGE_TAG: hello_go_http

stages:
  # - test
  - build
  - deploy

build_image:
  stage: build
  image: docker:24.0.4-cli
  services:
    - docker:24.0.4-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

# deploy:
#   stage: deploy
#   script:
#     - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@146.190.98.250



# format:
#   stage: test
#   script:
#     - go fmt $(go list ./... | grep -v /vendor/)
#     - go vet $(go list ./... | grep -v /vendor/)
#     - go test -race $(go list ./... | grep -v /vendor/)

# compile:
#   stage: build
#   script:
#     - mkdir -p mybinaries
#     - go build -o mybinaries ./...
#   artifacts:
#     paths:
#       - mybinaries

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
