image: golang:latest

variables:
  IMAGE_NAME: maiyzaza/demo-app
  IMAGE_TAG: latest

stages:
  - database
  - deleteImage
  - buildImage
  - deploy

database:
  stage: database
  script:
    -  |
        cat << EOF > ./.env
              REMOTE_DB_URL="$DB_CONNECTION"
        EOF
        ls -la
        cat .env

delete_image:
  stage: deleteImage
  image: docker:24.0.4-cli
  services:
    - docker:24.0.4-dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker ps -aq | xargs -I {} docker rm {}

build_image:
  stage: buildImage
  image: docker:24.0.4-cli
  services:
    - docker:24.0.4-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker images -q | xargs -I {} docker rmi {}
    - docker build -t $IMAGE_NAME:$IMAGE_TAG . 
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@146.190.98.250 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker ps -aq | xargs -I {} docker rm {} &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
